project_name: backend
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}-checksums.sha256"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - Merge pull request
      - Merge branch
archives:
  - name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Arch }}'
    homepage:  https://github.com/akosej/lookcopys
    description: Multiplatform application to monitor the copies that are made on USB devices
    maintainer: Edgar Javier <akosej9208@gmail.com>
    license: MIT
    vendor: Akosej
    formats:
      - deb